SubmitForm/Models/ErrorViewModel.cs
namespace SubmitForm.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

SubmitForm/Models/Form.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace SubmitForm.Models
{
    public class Form
    {
        [Required]
        public string FirstName { get; set; }
        [Required]
        public string LastName { get; set; }

        public Form(string firstName, string lastName)
        {
            FirstName = firstName;
            LastName = lastName;
        }
    }
}

SubmitForm/Controllers/FormController.cs
using System;
using System.Diagnostics;
using System.Net.Http.Json;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.AspNetCore.Mvc;
using SubmitForm.Models;
using Newtonsoft.Json;
using JsonSerializer = System.Text.Json.JsonSerializer;
using System.Text;

namespace SubmitForm.Controllers;

public class FormController : Controller
{
    private const string JsonFileName = "fullNames.json";

    public IActionResult Index()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Index(string firstName, string lastName)
    {
        Form nameJson = new Form(firstName, lastName);
        SimpleWrite(nameJson);

        ViewBag.Name = string.Format("Name: {0} {1}", firstName, lastName);
        return View();
    }

    private void SimpleWrite(object nameJson)
    {
        string nameString = JsonConvert.SerializeObject(nameJson);

        using (StreamWriter writer = System.IO.File.AppendText(JsonFileName))
        {
            writer.WriteLine(nameString);
        }
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

SubmitForm/Views/Form/Index.cshtml
@model IEnumerable<SubmitForm.Models.Form>

@{
    ViewData["Title"] = "Home Page";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="form" content="width=device-width"/>
    <title>Index</title>
</head>
<body>
    <form method="post" enctype="application/x-www-form-urlencoded" asp-controller="Form" asp-acion="index">
        <table>
            <tr>
                <td>@Html.DisplayNameFor(model => model.FirstName)</td>
                <td><input type="text" id="fName" name="firstName" /></td>
            </tr>
            <tr>
                <td>@Html.DisplayNameFor(model => model.LastName)</td>
                <td><input type="text" id="lName" name="lastName" /></td>
            </tr>
            <tr>
                <td></td>
                <td><input type="submit" value="Submit"/></td>
            </tr>
        </table>
        <hr />
        @*if open the comment, the result will display under the form*@
        @*@ViewBag.Name*@
    </form>
</body>
</html>

SubmitForm/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SubmitForm</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SubmitForm.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar  border-top border-bottom box-shadow mb-3">
            <div class="headContainer">
                <h2>SubmitForm</h2>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>